name: Test All Class Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  getAllTestFiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: bash ./.github/scripts/getFiles.sh
        shell: bash
  compileTestJava:
    name: Compile Test Java Classes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build
        run: ./gradlew :compileTestJava
  compileJava:
    name: Compile Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build
        run: ./gradlew :compileJava
  Javadoc:
    name: Javadoc test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: do all methods have javadoc
        run: ./gradlew :javadoc
  RunAllTestFiles:
    name: Test - ${{ matrix.class }}
    needs: [getAllTestFiles, compileJava, compileTestJava]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.getAllTestFiles.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run the Gradle class test
        id: testTheClass
        run: ./gradlew :test --tests ${{ matrix.class }}
